---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: ruby-release
- name: stemcell

params:
  RUBY_VERSION:

run:
  path: ruby-release/ci/tasks/test.sh
