azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - azs: [z1, z2, z3]
    cloud_properties:
      name: random
    gateway: 10.244.0.1
    range: 10.244.0.0/20
    reserved:
    - 10.244.0.1

compilation:
  workers: 2
  az: z1
  vm_type: default
  network: default
  reuse_compilation_vms: true
